---
title: My Paper
authors:
  - name: Megan Voss
    affiliation: Colorado State University
    roles: writing
    corresponding: true
  - name: Erica Mortland
    affiliation: Colorado State University
    roles: writing
    corresponding: false
bibliography: references.bib
---

Lab 5: Project Proposals
Megan Voss & Erica Mortland

Proposal 1: Wildfires and Droughts Correlation
Justification: 
	Due to humans’ effect and consumption of fossil fuels on our planet, climate change has a huge effect on our planet in many ways@cascio2018wildland, but especially with rising temperatures. Greenhouse gasses are ever increasing our average temperatures on Earth. Because of these rising temperatures, we tend to see a higher amount of wildfires and droughts@littell2016review. Since we know this, it would be interesting to investigate the relationship between these two natural disasters. This project is significant because it would relate wildfire data in the west to drought data. Do droughts cause wildfires, or at least does a pattern reveal itself when we investigate the timeline of these two disasters? Neither of these disasters are events we want to occur and by researching them and their qualities we may learn more about what causes them and how to prevent them. They affect a huge amount of people each time they occur and for the betterment of science and human life we want to investigate them further. 

Hypothesis/Question: Will an increase in droughts in the west specifically mean an increase in wildfires in the area as well?

Proposed Methods: 
	We will use two datasets for this study, one about wildfire data and one about drought data. We want to focus on the west more specifically and maybe especially Oregon if possible. We want to see trends in the increase of both of these and test for a relationship between the two sets of data. For this, we may want to run a correlation test of some sort. We could also potentially plot the two sets of data to see trends more visually as well. 
Datasets:
https://thredds.northwestknowledge.net/thredds/reacch_climate_MET_aggregated_catalog.html?dataset=agg_met_pdsi_1979_CurrentYear_CONUS 
https://datadryad.org/dataset/doi:10.5061/dryad.tmpg4f4x1 

Expected Outcomes: 
	For our results, we do expect to see a correlation between the two sets of data. Logically, it would make sense. Visually, there should be similar trends on a graph of drought frequency and wildfire frequency. Also with a correlation test, it would make sense to get a result of high correlation between the two. This outcome, if it is as predicted, would be especially helpful in predicting wildfires in the future. If droughts have a high correlation and therefore most likely causation of wildfires we may be more prepared in the event of a drought for a wildfire. Overall, it is useful to investigate these two disasters further due to how impactful they can be to us and our environment. 

References:
@cascio2018wildland 
Cascio, W. E. (2018). Wildland fire smoke and human health. Science of the total environment, 624, 586-595.
@littell2016review
Littell, J. S., Peterson, D. L., Riley, K. L., Liu, Y., & Luce, C. H. (2016). A review of the relationships between drought and forest fire in the United States. Global change biology, 22(7), 2353-2369.

Proposal 2: Examining the role of vegetation recovery in Post-fire Landscapes
Justification:
With wildfires becoming more prevalent, research on environmental recovery is as important as ever. Vegetation recovery is needed for post-fire ecosystem recovery, but increasing fire severity may limit regrowth, especially in dry and fire-prone regions (Stevens-Rumann et al., 2018). Understanding whether post-fire vegetation is recovering slower or transitioning to non-forest ecosystems is important for land management. If we understand the role of vegetation on fire recovery, it may help us learn more about how we can help burned ecosystems which is as important as ever. Especially in the west, where we are from, this is a big issue and vegetation is extremely important to the natural ecosystems there. 

Research Objective: To assess whether high-severity fire events lead to lower vegetation recovery rates over time.

Hypothesis: High-severity burn areas will have slower vegetation recovery compared to low-severity burns.

Proposed Methods
Datasets:
Fire severity dataset (Dillon et al., 2020) – already selected
MODIS Normalized Difference Vegetation Index (NDVI) time series (https://lpdaac.usgs.gov/products/mod13q1v006/)
Methods:
Extract NDVI values for burned areas in the years following fires, Compare NDVI recovery trajectories for high-severity vs. low-severity burns, and Conduct statistical tests (e.g., ANOVA) to determine significant differences in regrowth rates.
Expected Outcomes: We anticipate that areas burned at high severity will show lower post-fire NDVI values, which means a slower vegetation recovery rate or ecosystem transition to grasslands. This could have long-term meanings for carbon storage and biodiversity.
References:
@stevens2018evidence
Stevens-Rumann, C. S., Kemp, K. B., Higuera, P. E., Harvey, B. J., Rother, M. T., Donato, D. C., ... & Morgan, P. (2018). Evidence for declining forest resilience to wildfires under climate change. Ecology Letters, 21(2), 243-252. https://doi.org/10.1111/ele.12889

Proposal 3: The Influence of Human-Caused Fires on Fire Severity Trends
Justification: 
	Human-caused ignitions have altered fire seasonality and behavior, which has lead to more frequent and severe fires (Balch et al., 2017). While lightning-ignited fires tend to follow natural climate-driven cycles, human-started fires can introduce high-severity fire patterns in unexpected times and locations. Investigating whether human-ignited fires lead to greater fire severity than natural ignitions could be helpful for fire prevention strategies that we could utilize and implement as soon as possible.

Hypothesis: Human-caused fires will have higher average burn severity than other caused (natural) fires, leaving ecosystem damage for longer and negative impacts.

Proposed Methods: 
Fire severity dataset (Dillon et al., 2020) – already selected
Human vs. natural fire ignition dataset from National Interagency Fire Center (NIFC) (https://data-nifc.opendata.arcgis.com/)

Expected Outcomes: We expect to find that human-ignited fires exhibit higher severity in certain regions due to increased fuel accumulation, altered seasonality, or proximity to human activity. This finding could support targeted fire prevention policies.

References: 
@balch2017human
Balch, J. K., Bradley, B. A., Abatzoglou, J. T., Nagy, R. C., Fusco, E. J., & Mahood, A. L. (2017). Human-started wildfires expand the fire niche across the United States. Proceedings of the National Academy of Sciences, 114(11), 2946-2951 https://www.pnas.org/doi/full/10.1073/pnas.1617394114

Proposal 4: How does greenhouse gas rate change with population in Australia?
Justification: 
	Humans are a huge cause for greenhouse gas emissions in the world, and because of it, climate change is a major issue on our planet@gillingham2018cost. Greenhouse gasses trap heat, and therefore increase temperatures all across the globe. With population increase, this issue should only snowball@rosa2012human. However, it would be interesting to see the true correlation between population change and greenhouse gas emissions. This will give us more specific answers on each of our individual impacts on our planet. It may help us understand just how much mitigation must be done to lower greenhouse gasses. How big of a determiner is population in this? Is stopping population growth a main way to help this issue? Climate change must be researched more and by looking into this data we may gain insight into how to help the issue. Zooming in on a specific country/continent as well will give us more specific data.
	
Hypothesis/Question: With population increase in Australia, how do greenhouse gas emission rates change?

Proposed Methods: 
	We want to show the change in population as well as the change in greenhouse gas emissions in the same timeline. To do this a plot may be helpful, but we could also explore the datasets with a correlation test. Seeing just how much the two topics are related will be extremely helpful. Specifically looking at Australia will make this experiment more unique and narrow the scale of it.
Datasets:
https://datacommons.org/explore/#client=ui_related_topic&t=dc%2Ftopic%2FSustainability&p=country%2FAUS 
https://datacommons.org/explore#q=australia+population&client=ui_query 
Expected Outcomes: 
	Based on what we know, we are expecting to see an increase in greenhouse gas emissions with an increase in population. This would make sense since the cause of emissions are humans and more humans should equal more greenhouse gasses. However, I wouldn’t be too surprised if the correlation was low since there may be other factors like corporations, the government, and other entities that may have a bigger impact than individuals. 

References: 
@gillingham2018cost
Gillingham, K., & Stock, J. H. (2018). The cost of reducing greenhouse gas emissions. Journal of Economic Perspectives, 32(4), 53-72.
@rosa2012human
Rosa, E. A., & Dietz, T. (2012). Human drivers of national greenhouse-gas emissions. Nature climate change, 2(8), 581-586.





